// Generated by https://quicktype.io

export interface InstallProfile {
    _comment_:     string[];
    spec:          number;
    profile:       string;
    version:       string;
    path:          null;
    minecraft:     string;
    serverJarPath: string;
    data:          { [key: string]: Datum };
    processors:    Processor[];
    libraries:     Library[];
    icon:          string;
    json:          string;
    logo:          string;
    mirrorList:    string;
    welcome:       string;
}

export interface Datum {
    client: string;
    server: string;
}

export interface Library {
    name:      string;
    downloads: Downloads;
}

export interface Downloads {
    artifact: Artifact;
}

export interface Artifact {
    path: string;
    url:  string;
    sha1: string;
    size: number;
}

export interface Processor {
    sides?:    string[];
    jar:       string;
    classpath: string[];
    args:      string[];
    outputs?:  Outputs;
}

export interface Outputs {
    "{MC_SLIM}":  string;
    "{MC_EXTRA}": string;
}
